version: '2.3'

services: 
  sut:
    build: 
      context: ./
      target: testing
    depends_on:
       - mock-systemd
    volumes:
      - dbus:/shared/dbus
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/shared/dbus/system_bus_socket

  mock-systemd:
    environment:
      MOCK_SYSTEMD_UNITS: dummy.service
